### ISSUE TITLE
Erro ao utilizar a DLL

### ISSUE THREAD

**Issue by KcNirvana** [rmpt/CCReader#1]
Boa tarde,
Desde já obrigado pela disponibilização das DLLs.
Ao utilizar a DLL para ler os cartões obtenho este erro:
System.EntryPointNotFoundException: 'Não é possível localizar um ponto de entrada com o nome 'CSharp_PTEID_ReaderSet_initSDK__SWIG_1' na DLL 'pteidlibCS_Wrapper'.'

Na função Pteid.SetSODChecking(0)
Tenho o leitor de cartões ligado com um cartão inserido.
Podes ajudar?
Obrigado.

Abraço

**Comment by dalexfernandes** [comment]
> Boa tarde,
> Desde já obrigado pela disponibilização das DLLs.
> Ao utilizar a DLL para ler os cartões obtenho este erro:
> System.EntryPointNotFoundException: 'Não é possível localizar um ponto de entrada com o nome 'CSharp_PTEID_ReaderSet_initSDK__SWIG_1' na DLL 'pteidlibCS_Wrapper'.'
> 
> Na função Pteid.SetSODChecking(0)
> Tenho o leitor de cartões ligado com um cartão inserido.
> Podes ajudar?
> Obrigado.
> 
> Abraço

Boa tarde,
Também tenho a mesma situação, Já encontraram resolução?

Obrigado.

Até já

**Comment by KcNirvana** [comment]
@dalexfernandes 
Boas,
Consegui através do manual do middleware,
Em C#


> PTEID_ReaderSet.initSDK();      
> PTEID_EIDCard card;
> PTEID_ReaderContext context;
> PTEID_ReaderSet readerSet;
> PTEID_EId eid;
> readerSet = PTEID_ReaderSet.instance();
> context = PTEID_ReaderSet.instance().getReader();
> card = context.getEIDCard();
> eid = card.getID(); 
> string nome = eid.getGivenName(); 
> string nrCC = eid.getDocumentNumber();
> MessageBox.Show(nome);          
> PTEID_ReaderSet.releaseSDK();

Grande abraço
